import './style.css';

const cards = [
  { word: '予定', kana: 'よてい', meaning: 'plan; schedule', example: '週末の予定はありますか。', translation: 'Do you have plans for the weekend?' },
  { word: '間に合う', kana: 'まにあう', meaning: 'to be in time; make it', example: '電車に間に合いました。', translation: 'I made the train.' },
  { word: '連絡', kana: 'れんらく', meaning: 'contact; message', example: 'あとで連絡します。', translation: 'I will contact you later.' },
];
const listening = { text: 'すみません、駅はどちらですか。あの信号を右に曲がると、すぐ見えますよ。', question: 'What should the listener do?', answers: ['Turn right at the traffic light', 'Go straight for ten minutes', 'Take the next train'], correct: 0 };
const reading = { text: '図書館は来週の月曜日から金曜日まで、館内の工事のため休みになります。返却する本は、入口の返却ポストに入れてください。', question: 'What should you do with a library book next week?', answers: ['Return it at the front desk', 'Put it in the return box', 'Keep it until construction ends'], correct: 1 };
let state = JSON.parse(localStorage.getItem('n3-compass') || '{"streak":1,"done":0,"card":0,"mode":"home"}');
const save = () => localStorage.setItem('n3-compass', JSON.stringify(state));
const speak = text => { if ('speechSynthesis' in window) { speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = 'ja-JP'; u.rate = .82; speechSynthesis.speak(u); } };
const complete = () => { state.done += 1; state.streak = Math.max(state.streak, 1); save(); };
function nav(mode) { state.mode = mode; save(); render(); window.scrollTo({top:0, behavior:'smooth'}); }
function option(item, index, type) { return `<button class="answer" data-type="${type}" data-index="${index}">${item}</button>`; }
function home() { const minutes = Math.max(0, 20 - state.done * 5); return `
  <section class="hero"><span class="eyebrow">こんにちは, learner</span><h1>Small steps.<br><em>Real Japanese.</em></h1><p>Your bus-friendly N3 practice space—built for a focused 20-minute daily loop.</p><button class="primary" data-nav="today">Start today's session <span>→</span></button></section>
  <section class="stats"><div><strong>${state.streak}</strong><span>day streak</span></div><div><strong>${state.done}</strong><span>tasks done</span></div><div><strong>${minutes}</strong><span>min left</span></div></section>
  <section class="section-head"><div><span class="eyebrow">Today's path</span><h2>Keep moving forward</h2></div><span class="muted">~20 min</span></section>
  <div class="path">
    <button class="task" data-nav="words"><span class="task-icon coral">あ</span><span><b>Wake up your words</b><small>3 review cards · 5 min</small></span><i>→</i></button>
    <button class="task" data-nav="listen"><span class="task-icon gold">◖</span><span><b>Listen for the point</b><small>One natural-speed dialogue · 7 min</small></span><i>→</i></button>
    <button class="task" data-nav="speak"><span class="task-icon blue">◌</span><span><b>Say it out loud</b><small>Shadow a useful everyday phrase · 5 min</small></span><i>→</i></button>
  </div>
  <section class="insight"><span>✦</span><p><b>Coach's note</b> You remember more by retrieving, not rereading. Try answering before you tap.</p></section>`; }
function words() { const c = cards[state.card % cards.length]; return `<section class="top"><button class="back" data-nav="home">‹</button><div><span class="eyebrow">Word recall · ${state.card + 1}/${cards.length}</span><h2>Can you remember it?</h2></div></section><main class="practice"><div class="word-card"><span class="pill">N3 everyday Japanese</span><h1 lang="ja">${c.word}</h1><p class="kana" lang="ja">${c.kana}</p><button class="audio" data-speak="${c.word}">Listen <span>◖</span></button></div><button class="reveal" data-reveal>Show meaning</button><div class="meaning hidden"><h3>${c.meaning}</h3><p lang="ja">${c.example}</p><small>${c.translation}</small></div><div class="rating hidden"><button data-rate="again">Again</button><button data-rate="good">Got it</button></div></main>`; }
function drill(kind, data) { return `<section class="top"><button class="back" data-nav="home">‹</button><div><span class="eyebrow">${kind === 'listen' ? 'Listening · natural speed' : 'Reading · find the detail'}</span><h2>${kind === 'listen' ? 'Catch the key action' : 'Read with a purpose'}</h2></div></section><main class="practice"><article class="prompt"><button class="audio big" data-speak="${data.text}">Play dialogue <span>◖</span></button><p lang="ja" class="jp-text">${kind === 'read' ? data.text : 'Listen once. Then choose the action.'}</p></article><h3 class="question">${data.question}</h3><div class="answers">${data.answers.map((a,i) => option(a,i,kind)).join('')}</div><p class="feedback hidden"></p></main>`; }
function speakMode() { const phrase = 'すみません、もう一度お願いします。'; return `<section class="top"><button class="back" data-nav="home">‹</button><div><span class="eyebrow">Speaking · shadowing</span><h2>Make it yours</h2></div></section><main class="practice"><div class="shadow"><span class="pill">Useful in every conversation</span><p lang="ja">${phrase}</p><small>"Excuse me, one more time please."</small><button class="audio" data-speak="${phrase}">Hear it slowly <span>◖</span></button></div><ol class="steps"><li><b>Listen</b><span>Notice the rhythm, not every sound.</span></li><li><b>Shadow</b><span>Speak along with it, slightly behind.</span></li><li><b>Record</b><span>Use your phone's microphone to compare.</span></li></ol><button class="primary" data-record>Start speaking <span>◉</span></button><p class="record-status">Your recording stays on this device.</p></main>`; }
function today() { return `<section class="top"><button class="back" data-nav="home">‹</button><div><span class="eyebrow">Your 20-minute loop</span><h2>One thing at a time.</h2></div></section><main class="practice"><button class="focus-card" data-nav="words"><span>01</span><b>Recall 3 words</b><small>5 min</small></button><button class="focus-card" data-nav="listen"><span>02</span><b>Listen for one decision</b><small>7 min</small></button><button class="focus-card" data-nav="speak"><span>03</span><b>Shadow one phrase</b><small>5 min</small></button><button class="focus-card" data-nav="read"><span>04</span><b>Read a real-world notice</b><small>5 min</small></button></main>`; }
function render() { const views = { home, today, words, listen: () => drill('listen', listening), read: () => drill('read', reading), speak: speakMode }; document.querySelector('#app').innerHTML = `<div class="shell">${views[state.mode]()}</div><nav><button data-nav="home">⌂<small>Today</small></button><button data-nav="today">◫<small>Practice</small></button><button data-nav="words">あ<small>Words</small></button><button data-nav="speak">◌<small>Speak</small></button></nav>`; bind(); }
function bind() { document.querySelectorAll('[data-nav]').forEach(b => b.onclick = () => nav(b.dataset.nav)); document.querySelectorAll('[data-speak]').forEach(b => b.onclick = () => speak(b.dataset.speak)); const reveal = document.querySelector('[data-reveal]'); if (reveal) reveal.onclick = () => { document.querySelectorAll('.hidden').forEach(x => x.classList.remove('hidden')); reveal.classList.add('hidden'); }; document.querySelectorAll('[data-rate]').forEach(b => b.onclick = () => { if (b.dataset.rate === 'good') complete(); state.card = (state.card + 1) % cards.length; save(); render(); }); document.querySelectorAll('.answer').forEach(b => b.onclick = () => { const data = b.dataset.type === 'listen' ? listening : reading; const ok = Number(b.dataset.index) === data.correct; document.querySelectorAll('.answer').forEach(x => x.disabled = true); b.classList.add(ok ? 'correct' : 'wrong'); const f = document.querySelector('.feedback'); f.textContent = ok ? 'Exactly. Nice retrieval.' : `Not quite. The answer is: ${data.answers[data.correct]}.`; f.classList.remove('hidden'); if (ok) complete(); }); const record = document.querySelector('[data-record]'); if (record) record.onclick = () => recordSpeech(record); }
function recordSpeech(button) { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; const status = document.querySelector('.record-status'); if (!Recognition) { status.textContent = 'Use the iPhone keyboard microphone to record yourself—speech scoring is not supported in this browser.'; return; } const rec = new Recognition(); rec.lang = 'ja-JP'; rec.interimResults = false; button.textContent = 'Listening…'; rec.start(); rec.onresult = e => { status.textContent = `You said: ${e.results[0][0].transcript}`; button.textContent = 'Try once more'; complete(); }; rec.onerror = () => { status.textContent = 'Microphone access was unavailable. Try your phone keyboard microphone instead.'; button.textContent = 'Start speaking'; }; }
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();